# Generated by Django 3.2.4 on 2021-06-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originLocationCode', models.CharField(max_length=10, verbose_name='Origin location')),
                ('destinationLocationCode', models.CharField(max_length=10, verbose_name='Destination location')),
                ('departureDate', models.DateField(default=datetime.date.today, verbose_name='Departure date')),
                ('adultNumber', models.PositiveIntegerField(verbose_name='Number of adults')),
            ],
        ),
    ]
