# Generated by Django 3.2.4 on 2021-06-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0002_myflight_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflight',
            name='currency',
            field=models.CharField(choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'HRK')], default='2', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='myflight',
            name='destinationLocationCode',
            field=models.CharField(max_length=10, verbose_name='Destination IATA location'),
        ),
        migrations.AlterField(
            model_name='myflight',
            name='originLocationCode',
            field=models.CharField(max_length=10, verbose_name='Origin IATA location'),
        ),
    ]
