# Generated by Django 3.2.4 on 2021-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0003_auto_20210611_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflight',
            name='currency',
            field=models.CharField(choices=[('1', 'USD'), ('2', 'EUR'), ('3', 'HRK')], default='2', max_length=2, verbose_name='Currency'),
        ),
    ]
