# Generated by Django 3.2.4 on 2021-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0004_alter_myflight_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflight',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('HRK', 'HRK')], default='EUR', max_length=3, verbose_name='Currency'),
        ),
    ]
