# Generated by Django 3.2.4 on 2021-06-13 09:09

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originLocationCode', models.CharField(max_length=10, verbose_name='Origin IATA location')),
                ('destinationLocationCode', models.CharField(max_length=10, verbose_name='Destination IATA location')),
                ('departureDate', models.DateField(default=datetime.date.today, verbose_name='Departure date')),
                ('returnDate', models.DateField(default=datetime.date.today, verbose_name='Return date')),
                ('adultNumber', models.PositiveIntegerField(verbose_name='Number of adults')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('HRK', 'HRK')], default='EUR', max_length=3, verbose_name='Currency')),
                ('flightOffers', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default={}, size=None)),
                ('predictionFlights', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), default={}, size=None)),
                ('tripPurpose', models.CharField(default='', max_length=20000, verbose_name='Trip purpose')),
            ],
        ),
    ]
