# Generated by Django 3.2.4 on 2021-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflight',
            name='tripPurpose',
            field=models.CharField(default='', max_length=20, verbose_name='Trip purpose'),
        ),
    ]
